export const MusicDetails = {
  music_artist: [
    { imgurl: 'thumbnail.jpg', artist: 'Hiphop Tamizha' },
    { imgurl: 'thumbnail.jpg', artist: 'D.Imman' },
    { imgurl: 'thumbnail.jpg', artist: 'Vijay Antony' },
    { imgurl: 'thumbnail.jpg', artist: 'Pradeep Kumar' },
    { imgurl: 'thumbnail.jpg', artist: 'G. V. Prakash' },
    { imgurl: 'thumbnail.jpg', artist: 'P. Unnikrishnan' },
    { imgurl: 'thumbnail.jpg', artist: 'Harris Jayaraj' },
    { imgurl: 'thumbnail.jpg', artist: 'Karthik' },
    { imgurl: 'thumbnail.jpg', artist: 'Yuvan Shankar Raja' },
    { imgurl: 'thumbnail.jpg', artist: 'Udit Narayan' },
    { imgurl: 'thumbnail.jpg', artist: 'A.R. Rahaman' },
    { imgurl: 'thumbnail.jpg', artist: 'Anirudh Ravichander' },
  ],
  music_type: [
    { type: 'melody', imgurl: 'thumbnail.jpg' },
    { type: 'happy', imgurl: 'thumbnail.jpg' },
    { type: 'lovevibe', imgurl: 'thumbnail.jpg' },
    { type: 'love', imgurl: 'thumbnail.jpg' },
    { type: 'sad', imgurl: 'thumbnail.jpg' },
    { type: 'rap', imgurl: 'thumbnail.jpg' },
    { type: 'vibe', imgurl: 'thumbnail.jpg' },
    { type: 'drug', imgurl: 'thumbnail.jpg' },
  ],
  music_album: [
    { album: 'harrisvibe', imgurl: 'thumbnail.jpg'},
    { album: 'love', imgurl: 'thumbnail.jpg' },
    { album: 'yuvandurg', imgurl: 'thumbnail.jpg' },
    { album: 'sad', imgurl: 'thumbnail.jpg' },
    { album: 'vibe', imgurl: 'thumbnail.jpg' },
    { album: 'happyvibe', imgurl: 'thumbnail.jpg' },
    { album: 'lovedurg', imgurl: 'thumbnail.jpg' },
    { album: 'rap', imgurl: 'thumbnail.jpg' },
    { album: 'goosbums', imgurl: 'thumbnail.jpg' },
    { album: 'melody', imgurl: 'thumbnail.jpg' },
    { album: 'breakup', imgurl: 'thumbnail.jpg' },
    { album: 'alonevibe', imgurl: 'thumbnail.jpg' },
    { album: 'friend', imgurl: 'thumbnail.jpg' },
    { album: 'happy', imgurl: 'thumbnail.jpg' },
    { album: 'kuthusongs', imgurl: 'thumbnail.jpg' },
    { album: 'dad', imgurl: 'thumbnail.jpg' },
    { album: 'lovevibe', imgurl: 'thumbnail.jpg' },
    { album: 'onesidelove', imgurl: 'thumbnail.jpg' },
  ],
};
